### ISSUE TITLE
Container Build System Implementation

### ISSUE THREAD

**Issue by Shamiivan** [TheNewtonCapstone/newton-jetson-software#10]
### Limited Class Usage
Reserve object-oriented approach for specific components:
```python
class PackageTestRunner:
    """Test runner for package validation"""
    def __init__(self, container_name: str):
        self.container_name = container_name
        self.client = docker.from_env()
        self.results = []

    def run_test_suite(self, test_scripts):
        # Test execution logic
```

## Enhanced Package Structure
```
packages/
  ${package_name}/
    Dockerfile
    config.py 
    platforms.yaml  # Platform support configuration
    tests/
      test_import.py
      test_gpu.py
      test_samples.py
```

## Build System Functions
Add core functions:
```python
def get_system_info():
    """Get current system information."""
    return {
        'l4t_version': os.getenv('L4T_VERSION'),
        'jetpack_version': os.getenv('JETPACK_VERSION'),
        'platform': 'jetson' if is_jetson() else 'linux'
    }

def get_build_args(package_name: str, platform: str):
    """Get build arguments for package."""
    config = load_package_config(package_name)
    system = get_system_info()
    
    build_args = {
        'PYTHON_VERSION': '3.8',
        'CUDA_VERSION': system['cuda_version']
    }
    
    if platform == 'jetson':
        build_args.update({
            'L4T_VERSION': system['l4t_version'],
            'JETPACK_VERSION': system['jetpack_version']
        })
    
    return build_args

def build_container(package_name: str, base_image: str = None):
    """Build container for package."""
    build_args = get_build_args(package_name, get_system_info()['platform'])
    # Build implementation
```

### Phase 1: Core System
- [ ] Implement  build functions
- [ ] Create system info detection
- [ ] Setup package configuration parsing

### Phase 2: Test Framework
- [ ] Create PackageTestRunner class
- [ ] Implement test lifecycle management
- [ ] Add result collection system

### Phase 3: Platform Support
- [ ] Add Jetson-specific optimizations
- [ ] Implement Linux platform support
- [ ] Create platform detection

### Phase 4: Documentation
- [ ] Document build system architecture
- [ ] Add test framework usage guide
- [ ] Create package development guide
- [ ] Build flags

## Usage Examples
```bash
# Build package
./build.py pytorch

# Run tests
./build.py pytorch --test

# Build for specific platform
./build.py pytorch --platform linux
```

**Comment by Shamiivan** [comment]
done
